{{- if .Values.controller.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "foip-operator.fullname" . }}-controller
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list, watch]
- apiGroups: [foip.noshoes.xyz]
  resources: [failoverips]
  verbs: [get, list, watch, update, patch]
- apiGroups: [foip.noshoes.xyz]
  resources: [failoverips/status]
  verbs: [get, update, patch]
- apiGroups: [foip.noshoes.xyz]
  resources: [failoverprobes]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "foip-operator.fullname" . }}-controller
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "foip-operator.fullname" . }}-controller
subjects:
- kind: ServiceAccount
  name: {{ include "foip-operator.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "foip-operator.fullname" . }}-leader-election
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "foip-operator.fullname" . }}-leader-election
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "foip-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "foip-operator.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "foip-operator.fullname" . }}-secrets
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
rules:
{{- $secretNames := list }}
{{- range .Values.failoverIps }}
{{- $secretNames = append $secretNames .secretName }}
{{- end }}
{{- range .Values.failoverProbes }}
{{- with .credentialSecretRef }}
{{- $secretNames = append $secretNames .name }}
{{- end }}
{{- end }}
{{- $secretNames = concat $secretNames .Values.existingSecrets | uniq }}
- apiGroups: [""]
  resources: [secrets]
  verbs: [list, watch]
{{- if $secretNames }}
- apiGroups: [""]
  resources: [secrets]
  resourceNames: {{- toYaml $secretNames | nindent 4 }}
  verbs: [get]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "foip-operator.fullname" . }}-secrets
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "foip-operator.fullname" . }}-secrets
subjects:
- kind: ServiceAccount
  name: {{ include "foip-operator.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.nodeInterface.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "foip-operator.fullname" . }}-node-interface
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [nodes]
  verbs: [get, list, watch]
- apiGroups: [foip.noshoes.xyz]
  resources: [failoverips]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "foip-operator.fullname" . }}-node-interface
  labels:
    {{- include "foip-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "foip-operator.fullname" . }}-node-interface
subjects:
- kind: ServiceAccount
  name: {{ include "foip-operator.nodeInterface.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
