---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - foip.noshoes.xyz
  resources:
  - failoverips
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - foip.noshoes.xyz
  resources:
  - failoverips/status
  verbs:
  - get
  - patch
  - update
