apiVersion: netcup.foip.noshoes.xyz/v1
kind: FailoverIp
metadata:
  labels:
    app.kubernetes.io/name: foip-operator
    app.kubernetes.io/managed-by: kustomize
  name: failoverip-sample
spec:
  # TODO(user): Add fields here
