apiVersion: foip.noshoes.xyz/v1
kind: FailoverIp
metadata:
  labels:
    app.kubernetes.io/name: foip-operator
    app.kubernetes.io/managed-by: kustomize
  name: failoverip-sample
spec:
  ip: 1.2.3.4
  secretName: netcup-scp-credentials
  providerCooldownSeconds: 60
  stabilizationSeconds: 30
  recoveryPolicy: HoldDualOwnership
