apiVersion: v2
name: foip-operator
description: Assign a netcup failover IP to healthy nodes automatically.
type: application
version: 0.1.0
appVersion: 0.1.0
annotations:
  org.opencontainers.image.source: "https://github.com/niklasbeierl/foip-operator"
