apiVersion: v2
name: foip-operator
description: Assign a netcup failover IP to healthy nodes automatically.
type: application
version: 0.2.1
appVersion: 0.2.1
annotations:
  org.opencontainers.image.source: "https://github.com/thorion3006/foip-operator"
